apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trading-strategy-analysis
  namespace: quant-apps
spec:
  project: default
  source:
    repoURL: https://github.com/MiletoCarmelo/DEVOPS_TradingStrategyAnalysis.git
    targetRevision: prod
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: quant-apps
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    automated:
      selfHeal: true
      prune: true


# kubectl port-forward service/trading-strategy-analysis-service 8020:8020 -n quant-apps