apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-strategy-analysis-deployment
  namespace: argo-events # argocd  # Ensure this namespace exists
spec:
  selector:
    matchLabels:
      app: trading-strategy-analysis
  replicas: 1 # Number of pods to run
  template:
    metadata:
      labels:
        app: trading-strategy-analysis
    spec:
      containers:
      - name: trading-strategy-analysis
        image: <<AAA>>  # Placeholder for image
        ports:
        - containerPort: 8080  # Port the container listens on
        env:
        - name: PORT
          value: "8080"
