apiVersion: v1
kind: Service
metadata:
  name: trading-strategy-analysis-service
  namespace: argocd  # Ensure this namespace exists
spec:
  selector:
    app: trading-strategy-analysis  # Should match the deployment's labels
  type: ClusterIP  # Optional, default is ClusterIP
  ports:
  - port: 8020  # Port the service listens on
    protocol: TCP
    targetPort: 5000  # Should match the container's port


# ne pas oublier de lancer le port-forwarding : 
# -------------------------------------------
# kubectl port-forward service/trading-strategy-analysis-service 8020:8020 -n argocd