apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: quant-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        image: your-websocket-server-image:latest
        ports:
        - containerPort: 8020
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  namespace: quant-apps
spec:
  selector:
    app: websocket-server
  ports:
  - port: 8020
    targetPort: 8020