apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-strategy-analysis-deployment
  namespace: quant-apps  # Ensure this namespace exists
spec:
  selector:
    matchLabels:
      app: trading-strategy-analysis
  replicas: 4
  template:
    metadata:
      labels:
        app: trading-strategy-analysis
    spec:
      containers:
      - name: trading-strategy-analysis
        image: ghcr.io/miletocarmelo/tradingstrategyanalysis:latest  # Placeholder for image
        ports:
        - containerPort: 8090