apiVersion: v1
kind: Service
metadata:
  name: trading-strategy-analysis-service
  namespace: argocd  # Ensure this namespace exists
spec:
  # type: ClusterIP  # Optional, default is ClusterIP
  # selector:
  #  app: trading-strategy-analysis  # Should match the deployment's labels
  type: LoadBalancer
  selector:
    # app.kubernetes.io/name: argocd-server
    app: trading-strategy-analysis  # This should match the deployment's labels
  ports:
  - port: 8020  # Port the service listens on
    protocol: TCP
    targetPort: 5000  # Should match the container's port


# ne pas oublier de lancer le port-forwarding : 
# -------------------------------------------
# kubectl port-forward service/trading-strategy-analysis-service 8020:8020 -n quant-apps