apiVersion: v1
kind: Service
metadata:
  name: trading-strategy-analysis-service
  namespace: quant-apps  # Ensure this namespace exists
spec:
  selector:
    app: trading-strategy-analysis  # Should match the deployment's labels
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8090  # Should match the container's port
  type: ClusterIP  # Optional, default is ClusterIP
