apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: trading-strategy-analysis-deploy-
spec:
  entrypoint: deploy-taipy
  templates:
  - name: deploy-taipy
    steps:
    - - name: create-deployment
        template: kubectl-apply
        arguments:
          parameters:
          - name: manifest
            value: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: trading-strategy-analysis-deployment
                namespace: argo-events
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: trading-strategy-analysis
                template:
                  metadata:
                    labels:
                      app: trading-strategy-analysis
                  spec:
                    containers:
                    - name: trading-strategy-analysis
                      image: your-taipy-image:tag
                      ports:
                      - containerPort: 8080

  - name: kubectl-apply
    inputs:
      parameters:
      - name: manifest
    container:
      image: bitnami/kubectl
      command: [kubectl, apply, -f, -]
      stdin: "{{inputs.parameters.manifest}}"