apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: trading-strategy-analysis-webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 5000
        targetPort: 5000
  webhook:
    trading-strategy-analysis-trigger:
      port: "5000"
      endpoint: "/trading-strategy-analysis"
      method: POST