apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: trading-strategy-analysis-template
  namespace: argo-events
spec:
  entrypoint: create-and-redirect
  templates:
    - name: create-and-redirect
      steps:
        - - name: log-start
            template: log
            arguments:
              parameters:
                - name: message
                  value: "Starting workflow execution"
        - - name: create-pod
            template: create-pod
        - - name: log-pod-created
            template: log
            arguments:
              parameters:
                - name: message
                  value: "Pod created: {{steps.create-pod.outputs.result}}"
        - - name: wait-for-pod
            template: wait-for-pod
        - - name: log-pod-ready
            template: log
            arguments:
              parameters:
                - name: message
                  value: "Pod is ready: {{steps.wait-for-pod.outputs.result}}"
        - - name: redirect
            template: redirect
        - - name: log-end
            template: log
            arguments:
              parameters:
                - name: message
                  value: "Workflow completed, redirected to: {{steps.redirect.outputs.result}}"

    - name: create-pod
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            generateName: trading-strategy-analysis-
            labels:
              app: trading-strategy-analysis
          spec:
            containers:
            - name: trading-strategy-analysis
              image: ghcr.io/miletocarmelo/tradingstrategyanalysis:latest
              ports:
              - containerPort: 8080
      outputs:
        parameters:
          - name: result
            valueFrom:
              jsonPath: '{.metadata.name}'

    - name: wait-for-pod
      resource:
        action: get
        successCondition: status.phase == Running
        failureCondition: status.phase in (Failed, Unknown)
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{steps.create-pod.outputs.result}}"
            namespace: {{workflow.namespace}}
      outputs:
        parameters:
          - name: result
            valueFrom:
              jsonPath: '{.status.podIP}'

    - name: redirect
      http:
        url: "http://{{steps.wait-for-pod.outputs.result}}:8080"
      outputs:
        parameters:
          - name: result
            valueFrom:
              path: /url

    - name: log
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.14
        command: [echo]
        args: ["{{inputs.parameters.message}}"]