apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-default-role-binding
  namespace: argo-events
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo-events
roleRef:
  kind: Role
  name: argo-events-role  # Make sure this role exists and has necessary permissions
  apiGroup: rbac.authorization.k8s.io
