apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trading-strategy-sensor
  namespace: quant-apps
spec:
  dependencies:
    - name: trading-strategy-trigger
      eventSourceName: webhook
      eventName: trading-strategy-analysis
  triggers:
    - template:
        name: trading-strategy-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: trading-strategy-analysis-deployment
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: trading-strategy-analysis
                template:
                  metadata:
                    labels:
                      app: trading-strategy-analysis
                  spec:
                    containers:
                      - name: trading-strategy-analysis
                        image: <<AAA>>
                        ports:
                          - containerPort: 5000