apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trading-strategy-analysis-webhook
  namespace: quant-apps-events
spec:
  dependencies:
    - name: trading-strategy-analysis
      eventSourceName: trading-strategy-analysis-webhook
      eventName: trading-strategy-analysis
  triggers:
    - template:
        name: trading-strategy-analysis
        k8s:
          group: ""
          version: v1
          resource: pods
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                GenerateName: trading-strategy-analysis-
                labels:
                  app: trading-strategy-analysis
              spec:
                containers:
                  - name: trading-strategy-analysis
                    image: ghcr.io/miletocarmelo/tradingstrategyanalysis:latest
                    command: ["python3", "app.py"]
                    ports:
                      - containerPort: 12000
                restartPolicy: Never
          parameters:
            - src:
                dependencyName: trading-strategy-analysis