apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: trading-strategy-analysis-deploy
  namespace: argo  # Change this to match your Argo Workflows namespace
spec:
  entrypoint: deploy-taipy
  templates:
  - name: deploy-taipy
    steps:
    - - name: create-deployment
        template: kubectl-apply
        arguments:
          parameters:
          - name: manifest
            value: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: trading-strategy-analysis-deployment
                namespace: argo-events  # This is the target namespace for your deployment
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: trading-strategy-analysis
                template:
                  metadata:
                    labels:
                      app: trading-strategy-analysis
                  spec:
                    containers:
                    - name: trading-strategy-analysis
                      image: <<AAA>>  # Placeholder for image
                      ports:
                      - containerPort: 8080

  - name: kubectl-apply
    inputs:
      parameters:
      - name: manifest
    container:
      image: bitnami/kubectl
      command: [sh, -c]
      args: ['echo "{{inputs.parameters.manifest}}" | kubectl apply -f -']
