apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: trading-strategy-analysis-webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 8080
        targetPort: 8080
  webhook:
    trading-strategy-analysis-trigger:
      port: "8080"
      endpoint: "/trading-strategy-analysis"
      method: POST