apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: trading-strategy-analysis-template
  namespace: argo-events
spec:
  entrypoint: create-and-redirect
  arguments:
    parameters:
      - name: pod-name
  templates:
    - name: create-and-redirect
      steps:
        - - name: create-pod
            template: create-pod
        - - name: wait-for-pod
            template: wait-for-pod
        - - name: log-pod-ready
            template: log
            arguments:
              parameters:
                - name: message
                  value: "Pod {{workflow.parameters.pod-name}} is ready"
        - - name: tail-logs
            template: tail-logs
        - - name: redirect
            template: redirect
        - - name: log-redirect
            template: log
            arguments:
              parameters:
                - name: message
                  value: "Redirected to: {{steps.redirect.outputs.result}}"

    - name: create-pod
      resource:
        action: create
        setOwnerReference: true
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{workflow.parameters.pod-name | tolower}}"
            labels:
              app: trading-strategy-analysis
          spec:
            containers:
            - name: trading-strategy-analysis
              image: <<AAA>>
              ports:
              - containerPort: 8080

    - name: wait-for-pod
      resource:
        action: get
        successCondition: status.phase == Running
        failureCondition: status.phase in (Failed, Unknown)
        manifest: |
          apiVersion: v1
          kind: Pod
          metadata:
            name: "{{workflow.parameters.pod-name}}"
            namespace: {{workflow.namespace}}

    - name: tail-logs
      container:
        image: bitnami/kubectl
        command: [sh, -c]
        args: ["kubectl logs -f {{workflow.parameters.pod-name}} -n {{workflow.namespace}} & sleep 30; kill %1"]

    - name: redirect
      http:
        url: "http://{{workflow.parameters.pod-name}}:8080"
      outputs:
        parameters:
          - name: result
            valueFrom:
              path: /url

    - name: log
      inputs:
        parameters:
          - name: message
      container:
        image: alpine
        command: [echo]
        args: ["{{inputs.parameters.message}}"]