apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: trading-strategy-analysis-template
  namespace: argo-events
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: base-name
        value: "trading-strategy-analysis"
  templates:
    - name: main
      steps:
        - - name: generate-unique-name
            template: generate-unique-name
            arguments:
              parameters:
                - name: base-name
                  value: "{{workflow.parameters.base-name}}"
        - - name: create-and-run-child
            template: create-and-run-child
            arguments:
              parameters:
                - name: child-name
                  value: "{{steps.generate-unique-name.outputs.result}}"
        - - name: check-child-status
            template: check-child-status
            arguments:
              parameters:
                - name: child-name
                  value: "{{steps.create-and-run-child.outputs.parameters.child-workflow-name}}"
        - - name: wait-for-response
            template: wait-for-response
            arguments:
              parameters:
                - name: child-name
                  value: "{{steps.create-and-run-child.outputs.parameters.child-workflow-name}}"
      
    - name: generate-unique-name
      inputs:
        parameters:
          - name: base-name
      script:
        image: python:alpine3.6
        command: [python]
        source: |
          import re
          import uuid
          
          base_name = "{{inputs.parameters.base-name}}".lower()
          clean_name = re.sub(r'[^a-z0-9\-\.]', '-', base_name)
          clean_name = re.sub(r'^[^a-z0-9]+', '', clean_name)
          clean_name = re.sub(r'[^a-z0-9]+$', '', clean_name)
          if not clean_name:
              clean_name = "trading-strategy-analysis"
          
          unique_name = f"{clean_name}-{uuid.uuid4().hex[:6]}"
          
          # Ensure the name starts with an alphanumeric character
          if not unique_name[0].isalnum():
              unique_name = f"a{unique_name}"
          
          with open('/tmp/unique-name', 'w') as f:
              f.write(unique_name)
      outputs:
        parameters:
          - name: result
            valueFrom:
              path: /tmp/unique-name
    
    - name: create-and-run-child
      inputs:
        parameters:
          - name: child-name
      resource:
        action: create
        setOwnerReference: true
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: "child-{{inputs.parameters.child-name}}-"
            namespace: {{workflow.namespace}}
          spec:
            entrypoint: child-main
            templates:
              - name: child-main
                steps:
                  - - name: create-and-wait-pod
                      template: create-and-wait-pod
                  - - name: do-work
                      template: do-work
              - name: create-and-wait-pod
                resource:
                  action: create
                  setOwnerReference: true
                  successCondition: status.phase == Running
                  failureCondition: status.phase in (Failed, Unknown)
                  manifest: |
                    apiVersion: v1
                    kind: Pod
                    metadata:
                      generateName: "{{workflow.name}}-pod-"
                      labels:
                        app: trading-strategy-analysis
                    spec:
                      containers:
                      - name: trading-strategy-analysis
                        image: <<AAA>>
                        ports:
                        - containerPort: 8080
              - name: do-work
                container:
                  image: <<AAA>>
                  command: [sh, -c]
                  args: ["echo 'Performing analysis'; echo 'Analysis complete'"]
      outputs:
        parameters:
          - name: child-workflow-name
            valueFrom:
              jsonPath: '{.metadata.name}'
    
    - name: check-child-status
      inputs:
        parameters:
          - name: child-name
      resource:
        action: get
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            name: "{{inputs.parameters.child-name}}"
            namespace: {{workflow.namespace}}
      outputs:
        parameters:
          - name: status
            valueFrom:
              jsonPath: '{.status.phase}'

    - name: wait-for-response
      inputs:
        parameters:
          - name: child-name
      script:
        image: appropriate/curl
        command: [sh]
        source: |
          set -e
          POD_NAME=$(kubectl get pods -l workflows.argoproj.io/workflow={{inputs.parameters.child-name}} -o jsonpath='{.items[0].metadata.name}')
          POD_IP=$(kubectl get pod $POD_NAME -o jsonpath='{.status.podIP}')
          echo "Redirect URL: http://$POD_IP:8080"
          echo "Waiting for response... Press Ctrl+C to exit."
          while true; do
            if curl -s "http://$POD_IP:8080/status" | grep -q "completed"; then
              echo "Analysis completed. You can now access the results at http://$POD_IP:8080"
              break
            fi
            sleep 10
          done
    
    - name: log
      inputs:
        parameters:
          - name: message
      container:
        image: alpine
        command: [echo]
        args: ["{{inputs.parameters.message}}"]