apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: trading-strategy-analysis-webhook
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: trading-strategy-analysis
      eventSourceName: trading-strategy-analysis-webhook
      eventName: trading-strategy-analysis-trigger
  triggers:
    - template:
        name: trading-strategy-analysis
        k8s:
          operation: create
          source:
            resource:
              apiVersion: v1
              kind: Pod
              metadata:
                generateName: trading-strategy-analysis-
                labels:
                  app: trading-strategy-analysis
              spec:
                containers:
                  - name: trading-strategy-analysis
                    image: <<AAA>>
                    command: ["python3", "app.py"]
                    ports:
                      - containerPort: 5000
                    env:
                      - name: PORT
                        value: "5000"
                restartPolicy: Never
        parameters:
          - src:
              dependencyName: trading-strategy-analysis
            dest: spec.containers.0.env.0.value