name: Update Deployment

on:
  push:
    branches:
      - prod

env:
  REGISTRY_NAME: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # This will be in the format "owner/repo"
  IMAGE_TAG: latest

permissions:
  contents: write  # Allows reading files from the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull prod branch
        run: git pull origin prod

      - name: Set lowercase IMAGE_NAME
        id: set_image_name
        run: echo "IMAGE_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Remove "DEVOPS_" from IMAGE_NAME
        id: remove_devpos
        run: |
          IMAGE_NAME_NO_DEVOPS="${{ env.IMAGE_NAME_LOWER }}"
          IMAGE_NAME_NO_DEVOPS="${IMAGE_NAME_NO_DEVOPS/devops_/}"
          echo "IMAGE_NAME=${IMAGE_NAME_NO_DEVOPS}" >> $GITHUB_ENV

      - name: Print IMAGE_NAME
        run: echo "${{ env.IMAGE_NAME }}"

      - name: copy prod to deployment
        run: |
          cp ./dev/* ./prod/
  

      - name: Replace image placeholder
        run: |
          sed -i "s|<<AAA>>|${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" ./prod/deployment.yaml

      - name: Set user for git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit
        run: |
          git add ./prod/deployment.yaml
          git commit -m "Update ./prod/deployment.yaml with new image reference"

      - name: Push to prod
        run: |
          git push origin HEAD:prod
          # git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }} HEAD:prod