name: Update Deployment

on:
  push:
    branches:
      - prod

env:
  REGISTRY_NAME: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # This will be in the format "owner/repo"
  IMAGE_TAG: latest

permissions:
  contents: write  # Allows reading files from the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull prod branch
        run: git pull origin prod

      - name: Set lowercase IMAGE_NAME
        id: set_image_name
        run: echo "IMAGE_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Remove "DEVOPS_" from IMAGE_NAME
        id: remove_devpos
        run: |
          IMAGE_NAME_NO_DEVOPS="${{ env.IMAGE_NAME_LOWER }}"
          IMAGE_NAME_NO_DEVOPS="${IMAGE_NAME_NO_DEVOPS/devops_/}"
          echo "IMAGE_NAME=${IMAGE_NAME_NO_DEVOPS}" >> $GITHUB_ENV

      - name: Print IMAGE_NAME
        run: echo "${{ env.IMAGE_NAME }}"

      - name: copy prod to deployment
        run: |
          cp ./dev/deployment.yaml ./prod/deployment.yaml
          cp ./dev/service.yaml ./prod/service.yaml
          cp ./dev_event/sensor.yaml ./prod_event/sensor.yaml
          cp ./dev_event/event-source.yaml ./prod_event/event-source.yaml
          cp ./dev_event/ingress.yaml ./prod_event/ingress.yaml
          cp ./dev_event/redirection-workflow.yaml ./prod_event/redirection-workflow.yaml
          cp ./dev_event/role-binding.yaml ./prod_event/role-binding.yaml
          cp ./dev_workflow/ephemeral_pods.yaml ./prod_workflow/ephemeral_pods.yaml
          cp ./dev_workflow/websocket-server.yaml ./prod_workflow/websocket-server.yaml

      - name: Replace image placeholder in ./dev/deployment.yaml
        run: |
          sed -i "s|<<AAA>>|${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" ./prod/deployment.yaml

      - name: Replace image placeholder in ./dev_workflow/ephemeral_pods.yaml
        run: |
          sed -i "s|<<AAA>>|${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" ./prod_workflow/ephemeral_pods.yaml

      - name: Replace image placeholder in ./dev_event/sensor.yaml
        run: |
          sed -i "s|<<AAA>>|${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" ./prod_event/sensor.yaml

      - name: Replace image placeholder in ./dev_event/redirection-workflow.yaml
        run: |
          sed -i "s|<<AAA>>|${{ env.REGISTRY_NAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|g" ./prod_event/redirection-workflow.yaml

      - name: Replace image placeholder in ./dev_workflow/websocket-server.yaml
        run: |
          sed -i "s|<<BBB>>|your-websocket-server-image:${{ env.IMAGE_TAG }}|g" ./prod_workflow/websocket-server.yaml

      - name: Set user for git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit
        run: |
          git add .
          git commit -m "Update deployment"
          
      - name: Push to prod
        run: |
          git push origin HEAD:prod
          # git push https://x-access-token:${{ secrets.MY_PAT }}@github.com/${{ github.repository }} HEAD:prod